const TOKEN_EOF = -1
const TOKEN_TEXT = 0
const TOKEN_NEW_LINE = 1
const TOKEN_ELEMENT_NAME = 2
const TOKEN_CHORD = 3

module.exports = { TOKEN_EOF, TOKEN_TEXT, TOKEN_NEW_LINE, TOKEN_ELEMENT_NAME, TOKEN_CHORD }
